services:
    app:
        ports:
            - "9004:9004"  # Expose Xdebug port
            - "11111:11111"  # Add this line to publish PHPStan Pro's port
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: LearnHub_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/supervisor/supervisor_logs:/var/log/supervisor
            - ./docker/supervisor/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
        environment:
            - XDEBUG_CONFIG=client_host=host.docker.internal
            - XDEBUG_MODE=debug
            - XDEBUG_START_WITH_REQUEST=yes
            - XDEBUG_CLIENT_PORT=9003
            - XDEBUG_LOG=/tmp/xdebug.log
            - PHP_IDE_CONFIG=serverName=Docker
        networks:
            - learnhub
    db:
        image: mysql:latest
        container_name: LearnHub_mysql
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=learnhub
            - MYSQL_USER=learnhub
            - MYSQL_PASSWORD=learnhub
            - MYSQL_ROOT_PASSWORD=learnhub
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - learnhub

    nginx:
        image: nginx:latest
        container_name: LearnHub_nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - learnhub

    redis:
        image: redis:latest
        container_name: LearnHub_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        networks:
            - learnhub

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: LearnHub_meilisearch
        ports:
            - "7700:7700"
        environment:
            - MEILI_MASTER_KEY=your_master_key_here
        volumes:
            - meilisearchdata:/data.ms
        networks:
            - learnhub

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LearnHub_phpmyadmin
        platform: linux/x86_64
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - learnhub

    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: LearnHub_mailpit
        ports:
            - "8025:8025"  # Web interface
            - "1025:1025"  # SMTP server
        networks:
            - learnhub

networks:
    learnhub:
        driver: bridge

volumes:
    dbdata:
    redisdata:
    meilisearchdata:
