openapi: 3.0.3
info:
  title: 'LearnHub API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/website/blog-posts:
    get:
      summary: 'Website/List Blogs'
      operationId: websiteListBlogs
      description: " This endpoint list all blogpost from newest ones to the oldest.\n Additionally you may use ?title= query param to filter by title"
      parameters:
        -
          in: query
          name: title
          description: ''
          example: dolorem
          required: false
          schema:
            type: string
            description: ''
            example: dolorem
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      title: 'Quia pariatur rerum et sunt est quasi dolorem.'
                      slug: quia-pariatur-rerum-et-sunt-est-quasi-dolorem
                      excerpt: 'Fugit quod est expedita facilis. Est magnam quaerat ea quaerat dolores nisi molestiae. Et qui dolore corporis sit incidunt.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: "Hollie D'Amore"
                        last_name: Hammes
                        image: null
                    -
                      title: 'Iure et magnam dolorem voluptas.'
                      slug: iure-et-magnam-dolorem-voluptas
                      excerpt: 'Quidem voluptatem et et reiciendis. Voluptate sed vel dolorem quaerat sunt. Vero eos ea voluptas aut deleniti. Dolores commodi possimus unde voluptas.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Kenna Kassulke'
                        last_name: Boyer
                        image: null
                    -
                      title: 'Ut ut dolorem ad laboriosam.'
                      slug: ut-ut-dolorem-ad-laboriosam
                      excerpt: 'Facere eius sed sed quaerat velit quas. Quibusdam saepe adipisci libero sed. Natus expedita quia blanditiis qui voluptas odio esse. Impedit reprehenderit aperiam sit aut voluptatum.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: "Hollie D'Amore"
                        last_name: Hammes
                        image: null
                    -
                      title: 'Incidunt porro nulla dolores iure dolorem a autem.'
                      slug: incidunt-porro-nulla-dolores-iure-dolorem-a-autem
                      excerpt: 'Veniam quasi labore est vel. Sunt iste dolor earum. Sed in numquam consequatur.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Dr. Winona Bogisich'
                        last_name: Breitenberg
                        image: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        title: 'Quia pariatur rerum et sunt est quasi dolorem.'
                        slug: quia-pariatur-rerum-et-sunt-est-quasi-dolorem
                        excerpt: 'Fugit quod est expedita facilis. Est magnam quaerat ea quaerat dolores nisi molestiae. Et qui dolore corporis sit incidunt.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: "Hollie D'Amore"
                          last_name: Hammes
                          image: null
                      -
                        title: 'Iure et magnam dolorem voluptas.'
                        slug: iure-et-magnam-dolorem-voluptas
                        excerpt: 'Quidem voluptatem et et reiciendis. Voluptate sed vel dolorem quaerat sunt. Vero eos ea voluptas aut deleniti. Dolores commodi possimus unde voluptas.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Kenna Kassulke'
                          last_name: Boyer
                          image: null
                      -
                        title: 'Ut ut dolorem ad laboriosam.'
                        slug: ut-ut-dolorem-ad-laboriosam
                        excerpt: 'Facere eius sed sed quaerat velit quas. Quibusdam saepe adipisci libero sed. Natus expedita quia blanditiis qui voluptas odio esse. Impedit reprehenderit aperiam sit aut voluptatum.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: "Hollie D'Amore"
                          last_name: Hammes
                          image: null
                      -
                        title: 'Incidunt porro nulla dolores iure dolorem a autem.'
                        slug: incidunt-porro-nulla-dolores-iure-dolorem-a-autem
                        excerpt: 'Veniam quasi labore est vel. Sunt iste dolor earum. Sed in numquam consequatur.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Dr. Winona Bogisich'
                          last_name: Breitenberg
                          image: null
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          example: 'Quia pariatur rerum et sunt est quasi dolorem.'
                        slug:
                          type: string
                          example: quia-pariatur-rerum-et-sunt-est-quasi-dolorem
                        excerpt:
                          type: string
                          example: 'Fugit quod est expedita facilis. Est magnam quaerat ea quaerat dolores nisi molestiae. Et qui dolore corporis sit incidunt.'
                        tags:
                          type: array
                          example:
                            -
                              name: php
                            -
                              name: laravel
                            -
                              name: react
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: php
                        publish_date:
                          type: string
                          example: '2024-03-17'
                        author:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: "Hollie D'Amore"
                            last_name:
                              type: string
                              example: Hammes
                            image:
                              type: string
                              example: null
      tags:
        - Endpoints
      security: []
  /api/healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: down
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
