openapi: 3.0.3
info:
  title: 'LearnHub API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/website/blog-posts:
    get:
      summary: 'Website/List Blogs'
      operationId: websiteListBlogs
      description: " This endpoint list all blogpost from newest ones to the oldest.\n Additionally you may use ?title= query param to filter by title"
      parameters:
        -
          in: query
          name: title
          description: ''
          example: voluptas
          required: false
          schema:
            type: string
            description: ''
            example: voluptas
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      title: 'Sint dolore nesciunt et veniam sequi corrupti voluptas.'
                      slug: sint-dolore-nesciunt-et-veniam-sequi-corrupti-voluptas
                      excerpt: 'Necessitatibus voluptatem qui accusamus ratione. Veniam eum cumque enim totam modi qui. Autem assumenda velit et labore temporibus provident.'
                      tags:
                        -
                          tag_name: php
                        -
                          tag_name: laravel
                        -
                          tag_name: react
                      publish_date: '2024-03-17T16:34:53.000000Z'
                      author:
                        first_name: 'Prof. Damian Kautzer'
                        last_name: Thompson
                        img: null
                    -
                      title: 'Quia odio reprehenderit placeat molestiae voluptas aut voluptatem.'
                      slug: quia-odio-reprehenderit-placeat-molestiae-voluptas-aut-voluptatem
                      excerpt: 'Sapiente quas quis commodi voluptatibus officiis ea. Sint eos ea dolor voluptas modi velit. Minus autem qui quis corrupti repellat magnam.'
                      tags:
                        -
                          tag_name: php
                        -
                          tag_name: laravel
                        -
                          tag_name: react
                      publish_date: '2024-03-17T16:34:53.000000Z'
                      author:
                        first_name: 'Felicity Langosh'
                        last_name: Johns
                        img: null
                    -
                      title: 'Quisquam voluptas pariatur numquam eveniet eligendi quia.'
                      slug: quisquam-voluptas-pariatur-numquam-eveniet-eligendi-quia
                      excerpt: 'Voluptatem neque ipsum autem quidem et quia. Eius temporibus quo temporibus reiciendis sint dolorem.'
                      tags:
                        -
                          tag_name: php
                        -
                          tag_name: laravel
                        -
                          tag_name: react
                      publish_date: '2024-03-17T16:34:54.000000Z'
                      author:
                        first_name: 'Mr. Dock Stoltenberg'
                        last_name: Wilderman
                        img: null
                    -
                      title: 'Maiores est doloribus voluptas quo molestiae.'
                      slug: maiores-est-doloribus-voluptas-quo-molestiae
                      excerpt: 'Est sunt ratione illo possimus non. Assumenda atque atque aut aspernatur quidem atque. Ipsam eos et quia nostrum quam. Itaque et cupiditate laudantium.'
                      tags:
                        -
                          tag_name: php
                        -
                          tag_name: laravel
                        -
                          tag_name: react
                      publish_date: '2024-03-17T16:34:54.000000Z'
                      author:
                        first_name: 'Marie Heidenreich'
                        last_name: Pouros
                        img: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        title: 'Sint dolore nesciunt et veniam sequi corrupti voluptas.'
                        slug: sint-dolore-nesciunt-et-veniam-sequi-corrupti-voluptas
                        excerpt: 'Necessitatibus voluptatem qui accusamus ratione. Veniam eum cumque enim totam modi qui. Autem assumenda velit et labore temporibus provident.'
                        tags:
                          -
                            tag_name: php
                          -
                            tag_name: laravel
                          -
                            tag_name: react
                        publish_date: '2024-03-17T16:34:53.000000Z'
                        author:
                          first_name: 'Prof. Damian Kautzer'
                          last_name: Thompson
                          img: null
                      -
                        title: 'Quia odio reprehenderit placeat molestiae voluptas aut voluptatem.'
                        slug: quia-odio-reprehenderit-placeat-molestiae-voluptas-aut-voluptatem
                        excerpt: 'Sapiente quas quis commodi voluptatibus officiis ea. Sint eos ea dolor voluptas modi velit. Minus autem qui quis corrupti repellat magnam.'
                        tags:
                          -
                            tag_name: php
                          -
                            tag_name: laravel
                          -
                            tag_name: react
                        publish_date: '2024-03-17T16:34:53.000000Z'
                        author:
                          first_name: 'Felicity Langosh'
                          last_name: Johns
                          img: null
                      -
                        title: 'Quisquam voluptas pariatur numquam eveniet eligendi quia.'
                        slug: quisquam-voluptas-pariatur-numquam-eveniet-eligendi-quia
                        excerpt: 'Voluptatem neque ipsum autem quidem et quia. Eius temporibus quo temporibus reiciendis sint dolorem.'
                        tags:
                          -
                            tag_name: php
                          -
                            tag_name: laravel
                          -
                            tag_name: react
                        publish_date: '2024-03-17T16:34:54.000000Z'
                        author:
                          first_name: 'Mr. Dock Stoltenberg'
                          last_name: Wilderman
                          img: null
                      -
                        title: 'Maiores est doloribus voluptas quo molestiae.'
                        slug: maiores-est-doloribus-voluptas-quo-molestiae
                        excerpt: 'Est sunt ratione illo possimus non. Assumenda atque atque aut aspernatur quidem atque. Ipsam eos et quia nostrum quam. Itaque et cupiditate laudantium.'
                        tags:
                          -
                            tag_name: php
                          -
                            tag_name: laravel
                          -
                            tag_name: react
                        publish_date: '2024-03-17T16:34:54.000000Z'
                        author:
                          first_name: 'Marie Heidenreich'
                          last_name: Pouros
                          img: null
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          example: 'Sint dolore nesciunt et veniam sequi corrupti voluptas.'
                        slug:
                          type: string
                          example: sint-dolore-nesciunt-et-veniam-sequi-corrupti-voluptas
                        excerpt:
                          type: string
                          example: 'Necessitatibus voluptatem qui accusamus ratione. Veniam eum cumque enim totam modi qui. Autem assumenda velit et labore temporibus provident.'
                        tags:
                          type: array
                          example:
                            -
                              tag_name: php
                            -
                              tag_name: laravel
                            -
                              tag_name: react
                          items:
                            type: object
                            properties:
                              tag_name:
                                type: string
                                example: php
                        publish_date:
                          type: string
                          example: '2024-03-17T16:34:53.000000Z'
                        author:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: 'Prof. Damian Kautzer'
                            last_name:
                              type: string
                              example: Thompson
                            img:
                              type: string
                              example: null
      tags:
        - Endpoints
      security: []
  /api/healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: down
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
