openapi: 3.0.3
info:
  title: 'LearnHub API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/website/blog-posts:
    get:
      summary: 'Website/List Blogs'
      operationId: websiteListBlogs
      description: " This endpoint list all blogpost from newest ones to the oldest.\n Additionally you may use ?title= query param to filter by title"
      parameters:
        -
          in: query
          name: title
          description: ''
          example: quis
          required: false
          schema:
            type: string
            description: ''
            example: quis
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      title: 'Earum autem voluptas quisquam impedit qui sint aut.'
                      slug: earum-autem-voluptas-quisquam-impedit-qui-sint-aut
                      excerpt: 'Rem necessitatibus est dolor dolore. Natus commodi ut velit magni dicta repudiandae quidem.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Prof. Madeline Marvin'
                        last_name: Dietrich
                        image: null
                    -
                      title: 'Aut consectetur quisquam est et et.'
                      slug: aut-consectetur-quisquam-est-et-et
                      excerpt: 'Similique quasi possimus sequi quas. Nisi placeat odit quas doloremque eligendi rerum modi. Quisquam cum nisi iure quas voluptatibus aut optio. Minima dolores molestiae ullam ratione minima.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Prof. Madeline Marvin'
                        last_name: Dietrich
                        image: null
                    -
                      title: 'Qui placeat totam quis accusantium.'
                      slug: qui-placeat-totam-quis-accusantium
                      excerpt: 'Debitis labore quas ut deleniti qui. Sunt tempore rerum qui qui minus. Illum praesentium inventore voluptates minima quo. Non sint ratione esse. Expedita cum voluptatum eos debitis perferendis.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Tiana Larson'
                        last_name: Rolfson
                        image: null
                    -
                      title: 'Animi quis ipsa vel incidunt accusamus.'
                      slug: animi-quis-ipsa-vel-incidunt-accusamus
                      excerpt: 'Sunt quia et nam. Fuga quasi odit distinctio rerum autem omnis. Est et laborum soluta quod qui porro id. Quas aut iusto quo inventore perferendis.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Prof. Olin Schuster MD'
                        last_name: McKenzie
                        image: null
                    -
                      title: 'Earum quisquam ut officiis alias itaque voluptatem inventore.'
                      slug: earum-quisquam-ut-officiis-alias-itaque-voluptatem-inventore
                      excerpt: 'Et adipisci dolor labore. Est adipisci sit nihil nobis nisi autem corporis. Aut voluptatum vel itaque et atque aut quidem. Omnis aut exercitationem laudantium doloribus magnam in et.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Mariano Schiller Sr.'
                        last_name: Schmitt
                        image: null
                    -
                      title: 'Quis eum iste quod.'
                      slug: quis-eum-iste-quod
                      excerpt: 'Quidem sed porro molestiae dicta. Qui est iste est ut voluptatem in. Qui tempora modi eligendi ipsum sit. Et qui ab itaque in. Id sapiente voluptas quia quae nemo ut. Et quis sint enim.'
                      tags:
                        -
                          name: php
                        -
                          name: laravel
                        -
                          name: react
                      publish_date: '2024-03-17'
                      author:
                        first_name: 'Brendon Johns'
                        last_name: Kessler
                        image: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        title: 'Earum autem voluptas quisquam impedit qui sint aut.'
                        slug: earum-autem-voluptas-quisquam-impedit-qui-sint-aut
                        excerpt: 'Rem necessitatibus est dolor dolore. Natus commodi ut velit magni dicta repudiandae quidem.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Prof. Madeline Marvin'
                          last_name: Dietrich
                          image: null
                      -
                        title: 'Aut consectetur quisquam est et et.'
                        slug: aut-consectetur-quisquam-est-et-et
                        excerpt: 'Similique quasi possimus sequi quas. Nisi placeat odit quas doloremque eligendi rerum modi. Quisquam cum nisi iure quas voluptatibus aut optio. Minima dolores molestiae ullam ratione minima.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Prof. Madeline Marvin'
                          last_name: Dietrich
                          image: null
                      -
                        title: 'Qui placeat totam quis accusantium.'
                        slug: qui-placeat-totam-quis-accusantium
                        excerpt: 'Debitis labore quas ut deleniti qui. Sunt tempore rerum qui qui minus. Illum praesentium inventore voluptates minima quo. Non sint ratione esse. Expedita cum voluptatum eos debitis perferendis.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Tiana Larson'
                          last_name: Rolfson
                          image: null
                      -
                        title: 'Animi quis ipsa vel incidunt accusamus.'
                        slug: animi-quis-ipsa-vel-incidunt-accusamus
                        excerpt: 'Sunt quia et nam. Fuga quasi odit distinctio rerum autem omnis. Est et laborum soluta quod qui porro id. Quas aut iusto quo inventore perferendis.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Prof. Olin Schuster MD'
                          last_name: McKenzie
                          image: null
                      -
                        title: 'Earum quisquam ut officiis alias itaque voluptatem inventore.'
                        slug: earum-quisquam-ut-officiis-alias-itaque-voluptatem-inventore
                        excerpt: 'Et adipisci dolor labore. Est adipisci sit nihil nobis nisi autem corporis. Aut voluptatum vel itaque et atque aut quidem. Omnis aut exercitationem laudantium doloribus magnam in et.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Mariano Schiller Sr.'
                          last_name: Schmitt
                          image: null
                      -
                        title: 'Quis eum iste quod.'
                        slug: quis-eum-iste-quod
                        excerpt: 'Quidem sed porro molestiae dicta. Qui est iste est ut voluptatem in. Qui tempora modi eligendi ipsum sit. Et qui ab itaque in. Id sapiente voluptas quia quae nemo ut. Et quis sint enim.'
                        tags:
                          -
                            name: php
                          -
                            name: laravel
                          -
                            name: react
                        publish_date: '2024-03-17'
                        author:
                          first_name: 'Brendon Johns'
                          last_name: Kessler
                          image: null
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          example: 'Earum autem voluptas quisquam impedit qui sint aut.'
                        slug:
                          type: string
                          example: earum-autem-voluptas-quisquam-impedit-qui-sint-aut
                        excerpt:
                          type: string
                          example: 'Rem necessitatibus est dolor dolore. Natus commodi ut velit magni dicta repudiandae quidem.'
                        tags:
                          type: array
                          example:
                            -
                              name: php
                            -
                              name: laravel
                            -
                              name: react
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: php
                        publish_date:
                          type: string
                          example: '2024-03-17'
                        author:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: 'Prof. Madeline Marvin'
                            last_name:
                              type: string
                              example: Dietrich
                            image:
                              type: string
                              example: null
      tags:
        - Endpoints
      security: []
  /api/healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: down
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
