openapi: 3.0.3
info:
  title: 'LearnHub API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/website/blog-posts/list:
    get:
      summary: 'Website/List Blogs'
      operationId: websiteListBlogs
      description: " This endpoint list all blogpost from newest ones to the oldest.\n Additionally you may use ?title= query param to filter by title"
      parameters:
        -
          in: query
          name: title
          description: ''
          example: illum
          required: false
          schema:
            type: string
            description: ''
            example: illum
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      title: 'Dolorem ducimus molestiae voluptas voluptatem illum velit.'
                      slug: dolorem-ducimus-molestiae-voluptas-voluptatem-illum-velit
                      excerpt: 'Sit dolores quas ut qui aliquam hic consequatur. Voluptates ab dolor quis dolor sit sit. Placeat eligendi sed fugiat neque praesentium aut. Corrupti ut accusamus autem quaerat a amet neque.'
                      tags:
                        -
                          tag_name: php
                        -
                          tag_name: laravel
                        -
                          tag_name: react
                      publish_date: '2024-03-17T02:41:21.000000Z'
                      author:
                        first_name: 'Prof. Madalyn Donnelly V'
                        last_name: Upton
                        profile_img: null
                  links:
                    first: 'http://localhost/api/website/blog-posts/list?page=1'
                    last: 'http://localhost/api/website/blog-posts/list?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/website/blog-posts/list?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/website/blog-posts/list'
                    per_page: 15
                    to: 1
                    total: 1
                properties:
                  data:
                    type: array
                    example:
                      -
                        title: 'Dolorem ducimus molestiae voluptas voluptatem illum velit.'
                        slug: dolorem-ducimus-molestiae-voluptas-voluptatem-illum-velit
                        excerpt: 'Sit dolores quas ut qui aliquam hic consequatur. Voluptates ab dolor quis dolor sit sit. Placeat eligendi sed fugiat neque praesentium aut. Corrupti ut accusamus autem quaerat a amet neque.'
                        tags:
                          -
                            tag_name: php
                          -
                            tag_name: laravel
                          -
                            tag_name: react
                        publish_date: '2024-03-17T02:41:21.000000Z'
                        author:
                          first_name: 'Prof. Madalyn Donnelly V'
                          last_name: Upton
                          profile_img: null
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          example: 'Dolorem ducimus molestiae voluptas voluptatem illum velit.'
                        slug:
                          type: string
                          example: dolorem-ducimus-molestiae-voluptas-voluptatem-illum-velit
                        excerpt:
                          type: string
                          example: 'Sit dolores quas ut qui aliquam hic consequatur. Voluptates ab dolor quis dolor sit sit. Placeat eligendi sed fugiat neque praesentium aut. Corrupti ut accusamus autem quaerat a amet neque.'
                        tags:
                          type: array
                          example:
                            -
                              tag_name: php
                            -
                              tag_name: laravel
                            -
                              tag_name: react
                          items:
                            type: object
                            properties:
                              tag_name:
                                type: string
                                example: php
                        publish_date:
                          type: string
                          example: '2024-03-17T02:41:21.000000Z'
                        author:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: 'Prof. Madalyn Donnelly V'
                            last_name:
                              type: string
                              example: Upton
                            profile_img:
                              type: string
                              example: null
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/website/blog-posts/list?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/website/blog-posts/list?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/website/blog-posts/list?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/website/blog-posts/list'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 1
                      total:
                        type: integer
                        example: 1
      tags:
        - Endpoints
      security: []
  /api/healthcheck:
    get:
      summary: Healthcheck
      operationId: healthcheck
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: ''
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: down
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
